apiVersion: v1
kind: Service
metadata:
  name: testservice
  labels:
    app: nodeapp
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
